In [189]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

In [190]:
df =  pd.read_csv('../2017_07_07/TADPOLE_D1_D2.csv',low_memory=False)

In [191]:
df.head(3)

RID        PTID VISCODE  SITE  D1  D2 COLPROT ORIGPROT    EXAMDATE DX_bl  \
0    2  011_S_0002      bl    11   1   1   ADNI1    ADNI1  2005-09-08    CN   
1    3  011_S_0003      bl    11   1   0   ADNI1    ADNI1  2005-09-12    AD   
2    3  011_S_0003     m06    11   1   0   ADNI1    ADNI1  2006-03-13    AD   

   DXCHANGE   AGE PTGENDER  PTEDUCAT         PTETHCAT PTRACCAT  PTMARRY  \
0       1.0  74.3     Male        16  Not Hisp/Latino    White  Married   
1       3.0  81.3     Male        18  Not Hisp/Latino    White  Married   
2       3.0  81.3     Male        18  Not Hisp/Latino    White  Married   

   APOE4      FDG  PIB  AV45  CDRSB  ADAS11  ADAS13  MMSE  RAVLT_immediate  \
0    0.0  1.36926  NaN   NaN    0.0   10.67   18.67  28.0             44.0   
1    1.0  1.09079  NaN   NaN    4.5   22.00   31.00  20.0             22.0   
2    1.0  1.06360  NaN   NaN    6.0   19.00   30.00  24.0             19.0   

   RAVLT_learning  RAVLT_forgetting  RAVLT_perc_forgetting   FAQ  MOCA  \
0             4.0               6.0                54.5455   0.0   NaN   
1             1.0               4.0               100.0000  10.0   NaN   
2             2.0               6.0               100.0000  12.0   NaN   

   EcogPtMem  EcogPtLang  EcogPtVisspat  EcogPtPlan  EcogPtOrgan  \
0        NaN         NaN            NaN         NaN          NaN   
1        NaN         NaN            NaN         NaN          NaN   
2        NaN         NaN            NaN         NaN          NaN   

   EcogPtDivatt  EcogPtTotal  EcogSPMem  EcogSPLang  EcogSPVisspat  \
0           NaN          NaN        NaN         NaN            NaN   
1           NaN          NaN        NaN         NaN            NaN   
2           NaN          NaN        NaN         NaN            NaN   

   EcogSPPlan  EcogSPOrgan  EcogSPDivatt  EcogSPTotal      FLDSTRENG  \
0         NaN          NaN           NaN          NaN  1.5 Tesla MRI   
1         NaN          NaN           NaN          NaN  1.5 Tesla MRI   
2         NaN          NaN           NaN          NaN  1.5 Tesla MRI   

                                           FSVERSION  Ventricles  Hippocampus  \
0  Cross-Sectional FreeSurfer (FreeSurfer Version...    118233.0       8336.0   
1  Cross-Sectional FreeSurfer (FreeSurfer Version...     84599.0       5319.0   
2  Cross-Sectional FreeSurfer (FreeSurfer Version...     88580.0       5446.0   

   WholeBrain  Entorhinal  Fusiform  MidTemp        ICV        DX EXAMDATE_bl  \
0   1229740.0      4177.0   16559.0  27936.0  1984660.0        NL  2005-09-08   
1   1129830.0      1791.0   15506.0  18422.0  1920690.0  Dementia  2005-09-12   
2   1100060.0      2427.0   14400.0  16972.0  1906430.0  Dementia  2005-09-12   

   CDRSB_bl  ADAS11_bl  ADAS13_bl  MMSE_bl  RAVLT_immediate_bl  \
0       0.0      10.67      18.67       28                44.0   
1       4.5      22.00      31.00       20                22.0   
2       4.5      22.00      31.00       20                22.0   

   RAVLT_learning_bl  RAVLT_forgetting_bl  RAVLT_perc_forgetting_bl  FAQ_bl  \
0                4.0                  6.0                   54.5455     0.0   
1                1.0                  4.0                  100.0000    10.0   
2                1.0                  4.0                  100.0000    10.0   

    FLDSTRENG_bl                                       FSVERSION_bl  \
0  1.5 Tesla MRI  Cross-Sectional FreeSurfer (FreeSurfer Version...   
1  1.5 Tesla MRI  Cross-Sectional FreeSurfer (FreeSurfer Version...   
2  1.5 Tesla MRI  Cross-Sectional FreeSurfer (FreeSurfer Version...   

   Ventricles_bl  Hippocampus_bl  WholeBrain_bl  Entorhinal_bl  Fusiform_bl  \
0       118233.0          8336.0      1229740.0         4177.0      16559.0   
1        84599.0          5319.0      1129830.0         1791.0      15506.0   
2        84599.0          5319.0      1129830.0         1791.0      15506.0   

   MidTemp_bl     ICV_bl  MOCA_bl  EcogPtMem_bl  EcogPtLang_bl  \
0     27936.0  1984660.0      Na

In [192]:
columns = df.shape[1]
print(type(columns))

<class 'int'>


In [193]:
df_sample = df.sample(frac=0.1, random_state=1)
pd.set_option('display.max_columns', None)
name_columns=df.head(0)
#EXAMDATE	DX_bl	DXCHANGE	AGE	PTGENDER	PTEDUCAT	PTETHCAT	PTRACCAT	PTMARRY	
print(df['PTETHCAT'].head(10))

0    Not Hisp/Latino
1    Not Hisp/Latino
2    Not Hisp/Latino
3    Not Hisp/Latino
4    Not Hisp/Latino
5        Hisp/Latino
6        Hisp/Latino
7        Hisp/Latino
8        Hisp/Latino
9        Hisp/Latino
Name: PTETHCAT, dtype: object


In [194]:
print(df['DXCHANGE'].head(1))
'1=Stable:NL to NL, 2=Stable:MCI to MCI, 3=Stable:AD to AD, ' 
'4=Conv:NL to MCI, 5=Conv:MCI to AD, 6=Conv:NL to AD, ' 
'7=Rev:MCI to NL, 8=Rev:AD to MCI, 9=Rev:AD to NL, -1=Not available'

0    1.0
Name: DXCHANGE, dtype: float64


'7=Rev:MCI to NL, 8=Rev:AD to MCI, 9=Rev:AD to NL, -1=Not available'

In [195]:

#data = df[['PTGENDER','AGE','PTEDUCAT','APOE4','DXCHANGE','PTETHCAT','PTMARRY','PTEDUCAT','PTRACCAT','EXAMDATE']].copy()
data = df
print(data.shape)

#data.dropna(axis=0,inplace= True)
data['PTGENDER']= data['PTGENDER'].replace(['Male','Female'],[1,0])
data['APOE4']= data['APOE4'].astype(float)
data['AGE']= data['AGE'].astype(float)
data['PTETHCAT']= data['PTETHCAT'].replace(['Hisp/Latino','Not Hisp/Latino','Unknown'],[2,1,0]).astype(int)
data['PTMARRY']= data['PTMARRY'].replace(['Married','Widowed','Divorced','Never married','Unknown'],[0,1,2,3,4]).astype(int)
data['PTRACCAT'] = data['PTRACCAT'].replace(['White','More than one','Black','Asian', 'Am Indian/Alaskan','Hawaiian/Other PI', 'Unknown'],[0,1,2,3,4,5,6]).astype(int)
data['EXAMDATE'] = data['EXAMDATE']
#print(data['EXAMDATE'].unique())

# drop the columns in data they ate objet type
data = data.select_dtypes(exclude=['object'])
print(data.shape)
print(np.where(np.isnan(data)))
#data = np.nan_to_num(data)
print(np.where(np.isnan(data)))

print(data.shape)


(12741, 1907)
(12741, 84)
(array([    0,     0,     0, ..., 12740, 12740, 12740], dtype=int64), array([13, 14, 24, ..., 55, 74, 78], dtype=int64))
(array([    0,     0,     0, ..., 12740, 12740, 12740], dtype=int64), array([13, 14, 24, ..., 55, 74, 78], dtype=int64))
(12741, 84)


In [199]:
# Algorithme des k plus proches voisins
model = KNeighborsClassifier()
y = data['DXCHANGE']
X = data.drop('DXCHANGE', axis=1)
y = np.nan_to_num(y)
X= np.nan_to_num(X)


In [205]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

1.0
0.6673205178501374


In [206]:
param_grid = {'n_neighbors': np.arange(1, 25),'metric': ['euclidean', 'manhattan']}
grid = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid.fit(X_train, y_train)

C:\Users\antoi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\model_selection\_split.py:684: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(


GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})

In [207]:
print(grid.best_params_)
print(grid.best_score_)
print(grid.best_estimator_)
model = grid.best_estimator_
print(model.score(X_train,y_train))

{'metric': 'manhattan', 'n_neighbors': 1}
0.6400125905971918
KNeighborsClassifier(metric='manhattan', n_neighbors=1)
1.0


In [208]:
confusion_matrix(y_test, model.predict(X_test))


array([[513,  78, 123,  38,   1,   9,   0,   3,   0],
       [ 87, 418,  27,   8,   8,   0,   0,   6,   1],
       [129,  23, 569,  24,   6,  33,   0,   8,   1],
       [ 57,  12,  35, 192,   0,  23,   0,   0,   0],
       [  6,   8,   8,   1,   1,   0,   0,   0,   0],
       [  9,   4,  36,  22,   0,   5,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0],
       [  1,   1,   7,   0,   2,   0,   0,   3,   0],
       [  0,   0,   0,   1,   0,   1,   0,   0,   0]], dtype=int64)

In [209]:
def sick(model,PTGENDER=1,AGE=10,PTEDUCAT=4,APOE4=0):
    x= np.array([PTGENDER,AGE,PTEDUCAT,APOE4]).reshape(1,4)
    print(model.predict(x))
    print(model.predict_proba(x))